
POST http://localhost:8080/data
Content-Type: application/json

{
  "type": "FIRST",
  "data": {
    "first": "first"
  }
}

###

POST http://localhost:8080/data
Content-Type: application/json

{
  "type": "SECOND",
  "data": {
    "second": "second"
  }
}

###

POST http://localhost:8080/data
Content-Type: application/json

{
  "type": "THIRD",
  "data": {
    "third": "third"
  }
}

###

